function init() {
    panel()
        .name("solar_panel_1")
        .height(4 / 16.0)
        .generation("2")
        .capacity("16")
        .transfer("8").buildAndRegister()
        .langBuilder()
        .put("en_us", "Solar Panel 1 - Amethyst Tier")
        .put("fr_fr", "Panneau Solaire 1 - Tier Amethyste").build();
    panel()
        .name("solar_panel_2")
        .height(4 / 16.0)
        .generation("8")
        .capacity("64")
        .transfer("32").buildAndRegister()
        .langBuilder()
        .put("en_us", "Solar Panel 2 - Copper Tier")
        .put("fr_fr", "Panneau Solaire 2 - Niveau Cuivre").build();
    panel()
        .name("solar_panel_3")
        .height(4 / 16.0)
        .generation("16")
        .capacity("128")
        .transfer("64").buildAndRegister()
        .langBuilder()
        .put("en_us", "Solar Panel 3 - Iron Tier")
        .put("fr_fr", "Panneau Solaire 3 - Niveau Fer").build();
    panel()
        .name("solar_panel_4")
        .height(4 / 16.0)
        .generation("64")
        .capacity("512")
        .transfer("256").buildAndRegister()
        .langBuilder()
        .put("en_us", "Solar Panel 4 - Andesite Alloy Tier")
        .put("fr_fr", "Panneau Solaire 4 - Niveau Alliage d'Andésite").build();
    panel()
        .name("solar_panel_5")
        .height(4 / 16.0)
        .generation("128")
        .capacity("1024")
        .transfer("512").buildAndRegister()
        .langBuilder()
        .put("en_us", "Solar Panel 5 - Brass Tier")
        .put("fr_fr", "Panneau Solaire 5 - Niveau Brass").build();
    panel()
        .name("solar_panel_6")
        .height(4 / 16.0)
        .generation("512")
        .capacity("4096")
        .transfer("2048").buildAndRegister()
        .langBuilder()
        .put("en_us", "Solar Panel 6 - Vinteum Tier")
        .put("fr_fr", "Panneau Solaire 6 - Niveau Vinteum").build();
    panel()
        .name("solar_panel_7")
        .height(4 / 16.0)
        .generation("1024")
        .capacity("8192")
        .transfer("4096").buildAndRegister()
        .langBuilder()
        .put("en_us", "Solar Panel 7 - Quicksilver Tier")
        .put("fr_fr", "Panneau Solaire 7 - Niveau Quicksilver").build();
    panel()
        .name("solar_panel_8")
        .height(4 / 16.0)
        .generation("4096")
        .capacity("32768")
        .transfer("16384").buildAndRegister()
        .langBuilder()
        .put("en_us", "Solar Panel 8 - Black Iron Tier")
        .put("fr_fr", "Panneau Solaire 8 - Niveau Black Iron").build();
    panel()
        .name("solar_panel_9")
        .height(4 / 16.0)
        .generation("8192")
        .capacity("65536")
        .transfer("32768").buildAndRegister()
        .langBuilder()
        .put("en_us", "Solar Panel 9 - Ignitium Tier")
        .put("fr_fr", "Panneau Solaire 9 - Niveau Ignitium").build();
    panel()
        .name("solar_panel_10")
        .height(4 / 16.0)
        .generation("32768")
        .capacity("262144")
        .transfer("131072").buildAndRegister()
        .langBuilder()
        .put("en_us", "Solar Panel 10 - End Gobber Tier")
        .put("fr_fr", "Panneau Solaire 10 - Niveau End Gobber").build();
    panel()
        .name("solar_panel_11")
        .height(4 / 16.0)
        .generation("65536")
        .capacity("524288")
        .transfer("262144").buildAndRegister()
        .langBuilder()
        .put("en_us", "Solar Panel 11 - Nitro Crystal Tier")
        .put("fr_fr", "Panneau Solaire 11 - Niveau Nitro Crystal").build();
    panel()
        .name("solar_panel_12")
        .height(4 / 16.0)
        .generation("524288")
        .capacity("4194304")
        .transfer("2097152").buildAndRegister()
        .langBuilder()
        .put("en_us", "Solar Panel 12 - Chaos Tier")
        .put("fr_fr", "Panneau Solaire 12 - Niveau Chaos").build();
    panel()
        .name("solar_panel_13")
        .height(4 / 16.0)
        .generation("9223372036854775807")
        .capacity("9223372036854775807")
        .transfer("9223372036854775807").buildAndRegister()
        .langBuilder()
        .put("en_us", "Solar Panel 13 - Infinity Tier")
        .put("fr_fr", "Panneau Solaire 13 - Niveau Infinity").build();
}