#Roost XP Ratio
Ratio = 0.1
#Enable Crafting Grid for Guidebook
Enabled = true
#Roost Processing Speed in Seconds
"Roost Speed" = 10
#Breeder Processing Speed in Seconds
"Breeder Speed" = 20
#Trainer Processing Speed in Seconds
"Trainer Speed" = 15
#Soul Breeder Processing Speed in Seconds
"Soul Breeder Speed" = 20
#Soul Extractor Processing Speed in Seconds
"Soul Extractor Speed" = 5
#Set Max level for Tier 1 Chicken
"Max level Tier 1" = 30
#Set Max level for Tier 2 Chicken
"Max level Tier 2" = 30
#Set Max level for Tier 3 Chicken
"Max level Tier 3" = 30
#Set Max level for Tier 4 Chicken
"Max level Tier 4" = 30
#Set Max level for Tier 5 Chicken
"Max level Tier 5" = 30
#Set Max level for Tier 6 Chicken
"Max level Tier 6" = 30
#Set Max level for Tier 7 Chicken
"Max level Tier 7" = 30
#Set Max level for Tier 8 Chicken
"Max level Tier 8" = 30
#Set Max level for Tier 9 Chicken
"Max level Tier 9" = 30
#Set required XP for Levelup for Tier 1 Chicken
"Required XP Tier 1" = 256
#Set required XP for Levelup for Tier 2 Chicken
"Required XP Tier 2" = 256
#Set required XP for Levelup for Tier 3 Chicken
"Required XP Tier 3" = 256
#Set required XP for Levelup for Tier 4 Chicken
"Required XP Tier 4" = 256
#Set required XP for Levelup for Tier 5 Chicken
"Required XP Tier 5" = 256
#Set required XP for Levelup for Tier 6 Chicken
"Required XP Tier 6" = 256
#Set required XP for Levelup for Tier 7 Chicken
"Required XP Tier 7" = 256
#Set required XP for Levelup for Tier 8 Chicken
"Required XP Tier 8" = 256
#Set required XP for Levelup for Tier 9 Chicken
"Required XP Tier 9" = 256
#Set XP Amount for Vanilla Seeds
XP = 0
#Set XP Amount for Seed Tier 1
"Seed Tier 1" = 1
#Set XP Amount for Seed Tier 2
"Seed Tier 2" = 2
#Set XP Amount for Seed Tier 3
"Seed Tier 3" = 4
#Set XP Amount for Seed Tier 4
"Seed Tier 4" = 8
#Set XP Amount for Seed Tier 5
"Seed Tier 5" = 16
#Set XP Amount for Seed Tier 6
"Seed Tier 6" = 32
#Set XP Amount for Seed Tier 7
"Seed Tier 7" = 64
#Set XP Amount for Seed Tier 8
"Seed Tier 8" = 128
#Set XP Amount for Seed Tier 9
"Seed Tier 9" = 256

