
["Botany Pots Tiers Options"]
	#
	#Creative Botany Pot Speed
	#Range: > 1
	creativeBotanyPotSpeed = 64
	#
	#Ultra Botany Pot Speed
	#Range: > 1
	ultraBotanyPotSpeed = 32
	#
	#Ultra Botany Pot Multiplier
	#Range: > 1
	ultraBotanyPotMultiplier = 32
	#
	#Elite Botany Pot Speed
	#Range: > 1
	eliteBotanyPotSpeed = 16
	#
	#Elite Botany Pot Multiplier
	#Range: > 1
	eliteBotanyPotMultiplier = 16
	#
	#Creative Botany Pot Multiplier
	#Range: > 1
	creativeBotanyPotMultiplier = 64

